[package]
name = "stb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
anyhow = "1"
clap = { version = "3", features = ["derive"] }
qdrant-client = { version = "0.8", path = "../qdrant-rust-client" }
