[package]
name = "stb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
qstring = "0.7"
anyhow = "1"
clap = { version = "3", features = ["derive"] }
qdrant-client = { version = "0.8", git = "https://github.com/codabrink/qdrant-rust-client.git" }
tokio = { version = "1", features = ["full"] }
glob = "0.3"
rusqlite = "0.27"
regex = "1"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
