version: "3.9"
services:
  web:
    image: codabrink/stb
    environment:
      - QDRANT_HOST=qdrant
      - EMBEDDER_HOST=embedder
    ports:
      - 8080:8080
    volumes:
      - ./db.sqlite:/code/db.sqlite:Z
    depends_on:
      - embedder
      - qdrant
    networks:
      - stb-net
    restart: always
  embedder:
    image: codabrink/embedder
    deploy:
      resources:
        reservations:
          memory: 512M
    networks:
      - stb-net
    restart: always
  qdrant:
    image: "qdrant/qdrant"
    volumes:
      - ./qdrant.tar:/snapshots/qdrant.tar:Z
    command: "/qdrant/qdrant --force-snapshot --snapshot /snapshots/qdrant.tar:verses"
    networks:
      - stb-net
    ports:
      - 6334:6334
    restart: always

networks:
  stb-net:
    name: stb-net
